DROP TABLE IF EXISTS URLS;
DROP TABLE IF EXISTS WORDS;
DROP TABLE IF EXISTS WORD_LINKS;

CREATE TABLE URLS (
    ID SERIAL PRIMARY KEY,
    URL VARCHAR(100) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE WORDS (
    ID SERIAL PRIMARY KEY,
    WORD VARCHAR(100) NOT NULL
);

CREATE TABLE WORD_LINKS (
    ID SERIAL PRIMARY KEY,
    WORD_ID INTEGER NOT NULL,
    URL_ID INTEGER NOT NULL
);
